version: "3"

networks:
  d.net:
    driver: bridge

services:

  opure:
    image: canals/php:7.4
    environment:
      - VHOST_HOSTNAME=opure-paca.fr
      - VHOST_DOCROOT=/var/www
    ports:
      - "12080:80"
      - "12043:443"
    volumes:
      - ./www:/var/www

    working_dir: /var/www/
    networks:
      - d.net
    links:
      - mysql:db

  mysql:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=com
      - MYSQL_PASSWORD=com
      - MYSQL_DATABASE=opure
    volumes :
      - ./SQL:/var/sql
    networks:
      - d.net

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "12780:80"
    links:
      - mysql:db
    networks:
      - d.net
